name: todo_list_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Core
  equatable: ^2.0.5
  dartz: ^0.10.1
  google_fonts: ^4.0.3

  # State Management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  # Local Data
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


